spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cultureldb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/,file:src/main/resources/static/
local:
  file:
    path: /src/main/resources/static/files/
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method
  api-docs:
    path: /api-docs
